spring:
  datasource:
    url: jdbc:h2:tcp://localhost/C:\Users\김태완\aicareer/test
    username: sa
    password: a
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        #        show_sql: true
        format_sql: true

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace